### ISSUE TITLE
Does asynchbase support HBase 1.2?

### ISSUE THREAD

**Issue by jonbonazza** [OpenTSDB/asynchbase#136]
If not, are there plans to support it?

**Comment by jonbonazza** [comment]
Does it?

**Comment by saintstack** [comment]
Yes

**Comment by digvijay7** [comment]
+1
Is this official? Can we have it on the FAQ (which still says it is supported only up till 1.0)?

(Also, used it on local, with HBase 1.2.2 - seems to work fine for basic get and put operations)

**Comment by manolama** [comment]
Sort of official, @saintstack and his team found an extra exception type and handling that needs to be added. Otherwise it should be fine. 1.3 also has some more modifications we have to handle.

**Comment by karanmehta93** [comment]
Does it support HBase 1.3.1 as well? While running on my local machine, it threw random exceptions. 
If not, can anyone point me to relevant details so that I can put out a fix?

**Comment by karanmehta93** [comment]
From HBase 1.1, a bunch of new fields have been added in ClientProtos which are not currently available in AsyncHBase. These fields bring in additional changes to the client side to support them. 
For example, from 1.1, the results returned can be partial i.e. not all the KeyValues for a row might be returned in a single response. This essentially means that we need to handle it on client side to merge them into one result and then return them.
The current API's return Deferred<ArrayList<ArrayList<KeyValue>> which just returns all the KeyValues available from the result. This should work for most cases (probably will work for OpenTSDB as well since it doesn't care to get all rows together) but might not be a generic solution. The ScanRequest Proto also adds an additional field 'client_handles_partials' to deal with this stuff. If we don't provide users with the option of setting that bit in the Scanner then we are good.

Please suggest how we should handle it.
@manolama @saintstack

**Comment by manolama** [comment]
Good now since we support 1.2 and 1.3
